project:
  type: website
  output-dir: docs

website:
  title: Devin Davidson
  navbar:
    left:
      - href: landingpage.qmd
        text: Home
      - aboutme.qmd
      - projects.qmd
    
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/devindavidson46/devindavidson46.github.io

format:
  html:
    theme: zephyr # flatly, litera, lumen, lux, minty, pulse, sandstone, zephyr, quartz, yeti, cosmo, sketchy
    css: styles.css
    toc: true

execute: 
  freeze: auto

